import type { INodeProperties } from 'n8n-workflow';

export const ciJobsDescription: INodeProperties[] = [
		{
			"displayName": "Operation",
			"name": "operation",
			"type": "options",
			"noDataExpression": true,
			"displayOptions": {
				"show": {
					"resource": [
						"Ci Jobs"
					]
				}
			},
			"options": [
				{
					"name": "Get API v4 Job",
					"value": "Get API v4 Job",
					"action": "Retrieve a job by job token",
					"description": "Retrieves a job that was generated by a specified job token.",
					"routing": {
						"request": {
							"method": "GET",
							"url": "=/api/v4/job"
						}
					}
				}
			],
			"default": ""
		},
		{
			"displayName": "GET /api/v4/job",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Ci Jobs"
					],
					"operation": [
						"Get API v4 Job"
					]
				}
			}
		},
];
